version: '3.8'

services:
  app:
    build: .
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: npm run dev

volumes:
  node_modules:
